### ISSUE TITLE
 French data are not " up to date" (13/05/2020)

### ISSUE THREAD

**Issue by laudehenri** [OxCGRT/covid-policy-tracker#10]
Hello, very good job, we will use it soon for pedagogic and research purposes !!
thanks a lot
but unfortunately ...

btw i think that the French data are not " up to date": many restrictions are finished or less intense in France for 3 days (like school, transports ...) 13/05/2020

please have a look to : http://www.leparisien.fr/societe/coronavirus-dernier-jour-de-confinement-en-france-suivez-notre-direct-10-05-2020-8313930.php

best regards +
take care
Henri

**Comment by TobyPhillips** [comment]
Hi Henri, sorry it took me a week to respond. It seems like we have recorded a partial re-opening of schools from 12 May onwards (this may not have been in place when you wrote your message, most of our countries are always a few days out of date, we do not update 170 countries every single day).

But because there are still some measures on most dimensions, the stringency index only fell a little bit.

-Toby
